## Course 3 End-of-course project: Data exploration and hypothesis testing
In this activity, you will explore the data provided and conduct a hypothesis testing.

The purpose of this project is to demostrate knowledge of how to prepare, create, and analyze hypothesis tests.

The goal is to apply descriptive and inferential statistics, probability distributions, and hypothesis testing in Python.

This activity has three parts:

Part 1: Imports and data loading

What data packages will be necessary for hypothesis testing?
Part 2: Conduct hypothesis testing

How will descriptive statistics help you analyze your data?

How will you formulate your null hypothesis and alternative hypothesis?

Part 3: Communicate insights with stakeholders

What key business insight(s) emerge from your hypothesis test?

What business recommendations do you propose based on your results?

In [13]:
 ## Import packages for data manipulation
### YOUR CODE HERE ###


# Import packages for data visualization
### YOUR CODE HERE ###


# Import packages for statistical analysis/hypothesis testing
### YOUR CODE HERE ###
import pandas as pd
import numpy as np
from scipy import stats
from matplotlib import pyplot as plt
import seaborn as sns

In [20]:
filepath= r"C:\Users\chile\OneDrive\Desktop\MIT Lecture Notes\PYTHON DATA\tiktok_dataset.csv"
data= pd.read_csv(filepath)

## Task 2. Data exploration
Use descriptive statistics to conduct Exploratory Data Analysis (EDA).

Hint:
Inspect the first five rows of the dataframe.

In [22]:
# Display first few rows
### YOUR CODE HERE ###
data.head()

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,author_ban_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
0,1,claim,7017666017,59,someone shared with me that drone deliveries a...,not verified,under review,343296.0,19425.0,241.0,1.0,0.0
1,2,claim,4014381136,32,someone shared with me that there are more mic...,not verified,active,140877.0,77355.0,19034.0,1161.0,684.0
2,3,claim,9859838091,31,someone shared with me that american industria...,not verified,active,902185.0,97690.0,2858.0,833.0,329.0
3,4,claim,1866847991,25,someone shared with me that the metro of st. p...,not verified,active,437506.0,239954.0,34812.0,1234.0,584.0
4,5,claim,7105231098,19,someone shared with me that the number of busi...,not verified,active,56167.0,34987.0,4110.0,547.0,152.0

In [23]:
# Generate a table of descriptive statistics about the data
### YOUR CODE HERE ###
data.describe()

,#,video_id,video_duration_sec,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
count,19382.000000,1.938200e+04,19382.000000,19084.000000,19084.000000,19084.000000,19084.000000,19084.000000
mean,9691.500000,5.627454e+09,32.421732,254708.558688,84304.636030,16735.248323,1049.429627,349.312146
std,5595.245794,2.536440e+09,16.229967,322893.280814,133420.546814,32036.174350,2004.299894,799.638865
min,1.000000,1.234959e+09,5.000000,20.000000,0.000000,0.000000,0.000000,0.000000
25%,4846.250000,3.430417e+09,18.000000,4942.500000,810.750000,115.000000,7.000000,1.000000
50%,9691.500000,5.618664e+09,32.000000,9954.500000,3403.500000,717.000000,46.000000,9.000000
75%,14536.750000,7.843960e+09,47.000000,504327.000000,125020.000000,18222.000000,1156.250000,292.000000
max,19382.000000,9.999873e+09,60.000000,999817.000000,657830.000000,256130.000000,14994.000000,9599.000000

check and handle missing values

In [24]:
# Check for missing values
### YOUR CODE HERE ###
print(data.isnull().sum())

#                             0
claim_status                298
video_id                      0
video_duration_sec            0
video_transcription_text    298
verified_status               0
author_ban_status             0
video_view_count            298
video_like_count            298
video_share_count           298
video_download_count        298
video_comment_count         298
dtype: int64

In [25]:
# Drop rows with missing values

### YOUR CODE HERE ###
data=data.dropna(axis=0)

In [26]:
# Display first few rows after handling missing values

### YOUR CODE HERE ###
data.head()

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,author_ban_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
0,1,claim,7017666017,59,someone shared with me that drone deliveries a...,not verified,under review,343296.0,19425.0,241.0,1.0,0.0
1,2,claim,4014381136,32,someone shared with me that there are more mic...,not verified,active,140877.0,77355.0,19034.0,1161.0,684.0
2,3,claim,9859838091,31,someone shared with me that american industria...,not verified,active,902185.0,97690.0,2858.0,833.0,329.0
3,4,claim,1866847991,25,someone shared with me that the metro of st. p...,not verified,active,437506.0,239954.0,34812.0,1234.0,584.0
4,5,claim,7105231098,19,someone shared with me that the number of busi...,not verified,active,56167.0,34987.0,4110.0,547.0,152.0

You are interested in the relationship between verified_status and video_view_count. One approach is to examine the mean value of video_view_count for each group of verified_status in the sample data.

In [27]:
# Compute the mean `video_view_count` for each group in `verified_status`
### YOUR CODE HERE ###
data.groupby('verified_status')['video_view_count'].mean()

verified_status
not verified    265663.785339
verified         91439.164167
Name: video_view_count, dtype: float64

 ## Task 3. Hypothesis testing
Before you conduct your hypothesis test, consider the following questions where applicable to complete your code response:

Recall the difference between the null hypothesis and the alternative hypotheses. What are your hypotheses for this data project?
==> ENTER YOUR RESPONSE HERE (Double Click) There is a significant difference between the mean of the verfied users and un- verified users

Your goal in this step is to conduct a two-sample t-test. Recall the steps for conducting a hypothesis test:

State the null hypothesis and the alternative hypothesis
Choose a signficance level
Find the p-value
Reject or fail to reject the null hypothesis
==> ENTER YOUR NULL AND ALTERNATIVE HYPOTHESES HERE (Double Click) Ho= There is no difference in number of views of video posted by verified user and not verified users Ha= There is a difference in number of views of videos posted by verified and not verified users

In [28]:
# Conduct a two-sample t-test to compare means
### YOUR CODE HERE ###
not_verified= data[data['verified_status']== 'not verified']['video_view_count']
verified= data[data['verified_status']== 'verified']['video_view_count']

In [29]:
stats.ttest_ind(a= not_verified, b= verified, equal_var= False)

TtestResult(statistic=25.499441780633777, pvalue=2.6088823687177503e-120, df=1571.163074387424)

The p-VALUE IS 2.6088 is smaller than 5 therefore we reject the null hypothesis and concluse that There is a difference in number of views posted by verified user and number of views posted by un verified users